<?php

namespace AppBundle\Repository;

/**
 * schoolCrawlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class schoolCrawlerRepository extends \Doctrine\ORM\EntityRepository
{
}
