<?php

namespace AppBundle\Repository;

/**
 * scholarUniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scholarUniversityRepository extends \Doctrine\ORM\EntityRepository
{
}
