<?php

namespace AppBundle\Repository;

/**
 * universityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class universityRepository extends \Doctrine\ORM\EntityRepository
{
}
