house_index:
    path:     /
    defaults: { _controller: "AppBundle:houseAdminMenu:index" }
    methods:  GET

house_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:houseAdminMenu:show" }
    methods:  GET

house_new:
    path:     /new
    defaults: { _controller: "AppBundle:houseAdminMenu:new" }
    methods:  [GET, POST]

house_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:houseAdminMenu:edit" }
    methods:  [GET, POST]

house_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:houseAdminMenu:delete" }
    methods:  DELETE
